ffi1:
  - academic
  - apple
  - auricular6
  - bag2
  - bald34
  - balloons2
  - banes
  - bar1
  - black268
  - book119
  - book135
  - book137
  - book139
  - books17
  - books19
  - books20
  - books30
  - books8
  - boy21
  - bricks2
  - briefcase32
  - businessman216
  - businessman217
  - businessman56
  - businessman65
  - businessmen32
  - calculator40
  - calendar130
  - call36
  - call7
  - candy1
  - candy10
  - career
  - certificate2
  - checkboxmark
  - chemistry
  - chemistry1
  - circular114
  - circular116
  - class6
  - classroom
  - cleaning1
  - clipboard44
  - close13
  - cocktail15
  - cocktail7
  - coffee20
  - coins24
  - colors3
  - comfortable
  - comments16
  - compass58
  - computer135
  - computer136
  - computers
  - connected20
  - contacts1
  - copy12
  - croissant1
  - data39
  - data45
  - delivered
  - delivery35
  - descendant1
  - diploma
  - dislike
  - dna9
  - domain1
  - drink24
  - dwelling1
  - earth23
  - ecological2
  - edit12
  - education14
  - education17
  - education20
  - educational8
  - educative1
  - electric6
  - electrical7
  - electronic32
  - electronic51
  - elegant8
  - email20
  - facebook1
  - facebook30
  - female188
  - female189
  - female218
  - food23
  - fork27
  - gears3
  - gingerbread
  - girl16
  - glass15
  - good2
  - graduate11
  - graduate8
  - graduate9
  - graduates2
  - graduation20
  - graduation25
  - grocery10
  - halloween10
  - hammer7
  - hand132
  - handbag6
  - hands-shake
  - handshake1
  - hardbound
  - head21
  - hierarchical
  - homework
  - hot31
  - hot50
  - house25
  - important
  - index3
  - instructor
  - italian1
  - job
  - judge
  - keys
  - kids1
  - kindergarden
  - laptop88
  - lecture1
  - lecture2
  - like3
  - live2
  - magnifier12
  - magnifier13
  - male103
  - man183
  - man204
  - man315
  - man388
  - man397
  - man82
  - men9
  - milk8
  - mirrors
  - money13
  - mop1
  - mop2
  - movie19
  - multiple25
  - news
  - newspaper9
  - note20
  - open127
  - open135
  - open160
  - open161
  - owl10
  - package8
  - paperclip14
  - party
  - party1
  - pen38
  - pen39
  - pen43
  - pencil54
  - pencil66
  - pens
  - people30
  - personal5
  - persong
  - persons8
  - phone25
  - pie46
  - plate7
  - plug12
  - plugin
  - power20
  - power48
  - printer11
  - printer70
  - professor17
  - professor4
  - professor5
  - professor7
  - pumpkin2
  - puzzle25
  - question41
  - question42
  - quiz
  - regular2
  - remove9
  - resistor1
  - ruler14
  - running5
  - sandwich
  - scales2
  - school31
  - school35
  - school6
  - science2
  - scissors3
  - search4
  - search54
  - services
  - serving1
  - setting
  - sheep1
  - shop3
  - shopping66
  - shopping8
  - soccer32
  - social19
  - speech84
  - square74
  - stack21
  - stopwatch6
  - store
  - student13
  - student15
  - student40
  - students3
  - students5
  - students6
  - students7
  - sweet8
  - tags2
  - tags3
  - talking2
  - teacher12
  - teacher13
  - teacher4
  - teacher8
  - teacher9
  - test17
  - text87
  - textile
  - three115
  - thumb31
  - toilet1
  - tools
  - two174
  - two185
  - two28
  - users1
  - users2
  - users5
  - users6
  - verified9
  - view2
  - wifi10
  - wind15
  - winners2
  - woman83
  - worker12
  - worker2
  - worker4
  - workers
  - writing17
