
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons1_add_before: 
  - h2
  - h3
  - h4
  - separator
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
plugins:
  - table
  - fullscreen
  - advimage
  - heading
heading_clear_tag: p
width: "100%"
formats:
  boldred: {inline: "b", styles: {color: "red"}}
setup : function(fn) {
    // Add a custom button
    fn.addButton('firstname', {
        title : 'Member First Name',
        image : 'resources/scripts/tiny_mce/themes/advanced/img/firstname.gif',
        onclick : function() {
            // Add you own code to execute something on click
            fn.focus();
            fn.selection.setContent('{firstname}');
        }
    });
}


